version: "3.7"

services:
  frontend:
    build:
      context: .
      target: 'develop-stage'
    ports:
    - '8080:8080'
    volumes:
    - './frontend:/app'
    command: /bin/sh -c "npm run serve"
    networks:
      - red_ap
   
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - ./data/postgres:/var/postgresql/data:delegated
    ports:
    - '5432:5432'
    networks:
      - red_ap

  backend:
    image: yiisoftware/yii2-php:7.1-apache
    environment:
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: postgres
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASS}
      PHP_USER_ID: ${USER_UNIX_ID}
      ENABLE_GIT: 1
    volumes:
      - ./backend/composer/cache:/root/.composer/cache:delegated
      - ./backend/basic:/app:delegated
    
    ports:
      - 8000:80
    networks:
      - red_ap

networks:
  red_ap:
     driver: bridge
